grafana:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
    ruleSelectorNilUsesHelmValues: false
    additionalPrometheusRules: |
      - name: nginx-high-cpu
        groups:
          - name: nginx.rules
            rules:
              - alert: NginxHighCPU
                expr: |
                  sum(rate(container_cpu_usage_seconds_total{pod=~"nginx.*"}[2m])) > 0.8
                for: 1m
                labels:
                  severity: warning
                annotations:
                  summary: "High CPU usage on Nginx pod"
                  description: "Nginx pod CPU usage is above 80% for more than 1 minute."

alertmanager:
  enabled: true
  alertmanagerSpec:
    logLevel: info

# Alert rule for high CPU usage on nginx pods
# prometheusRule:
#   additionalRules:
#     - name: nginx-high-cpu
#       groups:
#         - name: nginx.rules
#           rules:
#             - alert: NginxHighCPU
#               expr: |
#                 sum(rate(container_cpu_usage_seconds_total{pod=~"nginx.*"}[2m])) > 0.8
#               for: 1m
#               labels:
#                 severity: warning
#               annotations:
#                 summary: "High CPU usage on Nginx pod"
#                 description: "Nginx pod CPU usage is above 80% for more than 1 minute."
